FROM fyneio/fyne-cross-images:linux
RUN apt-get update && \
    dpkg --add-architecture amd64 && \
    dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y libasound2-dev libasound2-dev:amd64 libasound2-dev:arm64 && \
    rm -rf /var/lib/apt/lists/*
